[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules','lib']
test = 'test/foundry'
cache_path = 'forge-cache'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config